# Generated by Django 5.1.2 on 2024-12-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(upload_to='HeroImage/'),
        ),
    ]
