# Generated by Django 5.1.2 on 2024-12-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_event_organizer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
